import type { ScanReport, ParsedDocument, SiteInfo, GenerateOutput } from './types.js';

const AI_CRAWLERS = [
  { name: 'GPTBot', description: 'OpenAI ChatGPT crawler' },
  { name: 'ChatGPT-User', description: 'ChatGPT browsing feature' },
  { name: 'ClaudeBot', description: 'Anthropic Claude crawler' },
  { name: 'PerplexityBot', description: 'Perplexity AI crawler' },
  { name: 'Google-Extended', description: 'Google AI/Gemini training data' },
  { name: 'Applebot-Extended', description: 'Apple Intelligence features' },
  { name: 'CCBot', description: 'Common Crawl (used by many AI models)' },
];

export function generateLlmsTxt(report: ScanReport, siteInfo: SiteInfo): string {
  const lines: string[] = [];

  lines.push(`# ${siteInfo.name}`);
  lines.push('');
  lines.push(`> ${siteInfo.description}`);
  lines.push('');

  if (report.pages.length > 0) {
    lines.push('## Pages');
    lines.push('');
    for (const page of report.pages) {
      const url = page.url;
      lines.push(`- [${page.title}](${url}): AI readability score ${page.scores.total}/100`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function generateLlmsFullTxt(report: ScanReport, pages: ParsedDocument[]): string {
  const lines: string[] = [];

  for (const page of pages) {
    lines.push(`## ${page.title}`);
    lines.push('');
    const maxChars = 5000;
    lines.push(page.rawText.slice(0, maxChars));
    if (page.rawText.length > maxChars) {
      lines.push(`\n[Content truncated: ${page.rawText.length} chars total, showing first ${maxChars}]`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

export function generateJsonLd(doc: ParsedDocument): object[] {
  const existing = new Set(doc.jsonLd.map((ld) => ld['@type']).filter(Boolean));
  const generated: object[] = [];

  // Add Article if not present and looks like an article
  if (!existing.has('Article') && !existing.has('TechArticle') && !existing.has('BlogPosting')) {
    if (doc.headings.length >= 2 && doc.paragraphs.length >= 3) {
      generated.push({
        '@context': 'https://schema.org',
        '@type': 'Article',
        name: doc.title,
        description: doc.metaTags['description'] || doc.paragraphs[0]?.slice(0, 160) || '',
        author: doc.metaTags['author'] ? { '@type': 'Person', name: doc.metaTags['author'] } : undefined,
        datePublished: doc.metaTags['article:published_time'] || undefined,
      });
    }
  }

  // Add FAQPage if question-style headings exist but no FAQ schema
  if (!existing.has('FAQPage')) {
    const questionHeadings = doc.headings.filter((h) => h.text.endsWith('?'));
    if (questionHeadings.length >= 2) {
      const mainEntity = questionHeadings.map((q) => {
        // Find paragraphs that likely answer this question by searching rawText
        // Look for content between this heading and the next heading
        const qIdx = doc.rawText.indexOf(q.text);
        let answer = 'Answer not extracted.';
        if (qIdx !== -1) {
          const afterQuestion = doc.rawText.slice(qIdx + q.text.length, qIdx + q.text.length + 500).trim();
          // Take first sentence-like chunk
          const firstChunk = afterQuestion.split(/\n\n|\.\s/)[0]?.trim();
          if (firstChunk && firstChunk.length > 10) {
            answer = firstChunk.endsWith('.') ? firstChunk : firstChunk + '.';
          }
        }
        return {
          '@type': 'Question',
          name: q.text,
          acceptedAnswer: { '@type': 'Answer', text: answer },
        };
      });

      generated.push({
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        name: `${doc.title} FAQ`,
        mainEntity,
      });
    }
  }

  // Add BreadcrumbList from nav links if not present
  if (!existing.has('BreadcrumbList')) {
    const navLinks = doc.links.filter((l) => l.href.startsWith('/') && l.text.length > 0).slice(0, 5);
    if (navLinks.length >= 2) {
      generated.push({
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: navLinks.map((link, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: link.text,
          item: link.href,
        })),
      });
    }
  }

  return generated;
}

export function generateRobotsTxtSuggestions(existingRobots: string | null): string[] {
  const suggestions: string[] = [];
  const existing = existingRobots || '';

  suggestions.push('# AI Crawler Configuration');
  suggestions.push('# Generated by aeo-cli');
  suggestions.push('');

  for (const crawler of AI_CRAWLERS) {
    const isConfigured = new RegExp(`User-agent:\\s*${crawler.name}`, 'i').test(existing);
    if (!isConfigured) {
      suggestions.push(`# ${crawler.description}`);
      suggestions.push(`User-agent: ${crawler.name}`);
      suggestions.push('Allow: /');
      suggestions.push('');
    }
  }

  if (!existing.includes('llms.txt') && !existing.includes('llms-full.txt')) {
    suggestions.push('# Point AI crawlers to your llms.txt');
    suggestions.push('# Add to your site: <link rel="llms-txt" href="/llms.txt">');
  }

  return suggestions;
}

export function generate(report: ScanReport, pages: ParsedDocument[], siteInfo: SiteInfo, existingRobots?: string | null): GenerateOutput {
  return {
    llmsTxt: generateLlmsTxt(report, siteInfo),
    llmsFullTxt: generateLlmsFullTxt(report, pages),
    jsonLd: pages.flatMap((p) => generateJsonLd(p)),
    robotsTxtSuggestions: generateRobotsTxtSuggestions(existingRobots ?? null),
  };
}
